// Legacy redirect map — ported from feat/astro-migration vercel.json (485 entries)
// Corrections applied 2026-09-04:
//   - 13 stale /jewelry/[name-slug] destinations updated to live SKU-based URLs
//   - 2 query-param destinations (/collection?cat=) simplified to /collection
//   - /shop/:slug patterns → /archive (historical catalog, not /collection)
// Corrections applied 2026-09-05:
//   - /retailers → /contact restored (new site has no /retailers index page)
//   - 9 missing WP blog post slugs added → /blog
// Corrections applied 2026-09-17 — every destination was audited against the
// live routes, the products table and the blog_posts table; 84 entries pointed
// at URLs that 404:
//   - 9 product destinations still used SKU slugs (deriveSlug switched products
//     to name-derived slugs); repointed to the live slug, except in101 which no
//     longer exists as a product → /jewelry/necklaces
//   - 27 retailer aliases (per-location and per-domain variants) collapsed onto
//     the 13 slugs lib/data/retailers.ts actually defines; the 2 with no current
//     retailer → /contact
//   - 4 blog slugs are not in blog_posts at all → /blog
//   - /collection, /retailers, /press, /video-gallery are redirect targets with
//     no page behind them → /jewelry, /contact, /about-bez-ambar, /archive
// Corrections applied 2026-09-29 — the /journal bucket was emptied (Kevin:
// "the blog redirects should go to /blog/{slug} not /journal/"). 128 old WP
// keyword URLs (256 rules with their trailing-slash twins) pointed at /journal,
// which is NOT the editorial index — it is a client-side Curator.io Instagram
// embed with zero articles in its server HTML. /blog is the real index (132
// live posts). Nothing points at /journal any more.
//   - 48 sources matched a specific live post → /blog/<slug> (26 distinct posts)
//   - 80 sources had no post that actually covers their subject → /blog
// Only 2 of the 128 had a slug-equal post — the new blog's slugs were rewritten,
// so this was a per-URL subject match, not a mechanical one. City pages
// (/engagement-rings-boston), competitor names (/turgeon-raine,
// /international-diamond-center-*), single-piece product pages and numeric
// slugs (/552, /599) all go to the index deliberately: a wrong specific
// redirect is a worse signal than the index. Low-confidence matches were
// demoted to the index for the same reason.
// Guard: `node scripts/check-redirects.js` re-runs this validation.

import type { NextConfig } from 'next'

type Redirect = Awaited<ReturnType<NonNullable<NextConfig['redirects']>>>[number]

export const REDIRECTS: Redirect[] = [
    { source: '/catalogs', destination: '/jewelry', permanent: true },
    { source: '/catalogs/', destination: '/jewelry', permanent: true },
    { source: '/552', destination: '/blog', permanent: true },
    { source: '/552/', destination: '/blog', permanent: true },
    { source: '/599', destination: '/blog', permanent: true },
    { source: '/599/', destination: '/blog', permanent: true },
    { source: '/about-the-designer', destination: '/about-bez-ambar', permanent: true },
    { source: '/about-the-designer/', destination: '/about-bez-ambar', permanent: true },
    { source: '/the-bez-ambar-story-4', destination: '/about-bez-ambar', permanent: true },
    { source: '/the-bez-ambar-story-4/', destination: '/about-bez-ambar', permanent: true },
    { source: '/the-bez-ambar-story', destination: '/about-bez-ambar', permanent: true },
    { source: '/our-story', destination: '/about-bez-ambar', permanent: true },
    { source: '/about', destination: '/about-bez-ambar', permanent: true },
    { source: '/bez-ambar-jewelry-design-videos-2', destination: '/archive', permanent: true },
    { source: '/bez-ambar-jewelry-design-videos-2/', destination: '/archive', permanent: true },
    { source: '/diamond-education-2', destination: '/diamond-education', permanent: true },
    { source: '/diamond-education-2/', destination: '/diamond-education', permanent: true },
    { source: '/diamond-anatomy', destination: '/diamond-education', permanent: true },
    { source: '/diamond-anatomy/', destination: '/diamond-education', permanent: true },
    { source: '/bezwarranty', destination: '/warranty', permanent: true },
    { source: '/bezwarranty/', destination: '/warranty', permanent: true },
    { source: '/ring-size-chart/', destination: '/ring-size-chart', permanent: true },
    { source: '/pdf_lv_category/bez-betzalel-ambar-press', destination: '/about-bez-ambar', permanent: true },
    { source: '/pdf_lv_category/bez-betzalel-ambar-press/', destination: '/about-bez-ambar', permanent: true },

    // WordPress `timeline` custom post type — brand-invention history, folded into the About timeline
    { source: '/timeline/quadrillion', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/quadrillion/', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/the-debeers-award-winner', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/the-debeers-award-winner/', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/invisible-setting', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/invisible-setting/', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/boundless-setting', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/boundless-setting/', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/divine-cut', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/divine-cut/', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/blaze-cut', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/blaze-cut/', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/micro-pave', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/micro-pave/', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/ambar-diamonds', destination: '/about-bez-ambar', permanent: true },
    { source: '/timeline/ambar-diamonds/', destination: '/about-bez-ambar', permanent: true },
    { source: '/bloom', destination: '/collection/bloom', permanent: true },
    { source: '/our-blog', destination: '/blog', permanent: true },
    { source: '/our-blog/', destination: '/blog', permanent: true },
    { source: '/shop', destination: '/jewelry', permanent: true },
    { source: '/shop/', destination: '/jewelry', permanent: true },
    { source: '/shop/page/:num', destination: '/jewelry', permanent: true },
    { source: '/product/in100', destination: '/jewelry/necklaces/trait-princess-cut-necklace', permanent: true },
    { source: '/product/in101', destination: '/jewelry/necklaces', permanent: true },
    { source: '/product/c0625', destination: '/jewelry/bands', permanent: true },
    { source: '/product/c0508', destination: '/jewelry/necklaces/cascade-necklace', permanent: true },
    { source: '/product/c0536', destination: '/jewelry/rings/trilogy-oval-yellow-pear-sides-ring', permanent: true },
    { source: '/product/1c36', destination: '/jewelry/rings', permanent: true },
    { source: '/product/c0747', destination: '/jewelry/rings/trilogy-oval-pear-sides-ring', permanent: true },
    { source: '/product/c0754', destination: '/jewelry/bracelets/extent-asscher-33-bracelet', permanent: true },
    { source: '/product/c0834', destination: '/jewelry/bracelets/extent-emerald-40-bracelet', permanent: true },
    { source: '/product/c0755', destination: '/jewelry/bracelets', permanent: true },
    { source: '/product/c0825', destination: '/jewelry/bracelets', permanent: true },
    { source: '/product/c0728', destination: '/jewelry/rings/fleuron-ring', permanent: true },
    { source: '/product/b9792', destination: '/jewelry/rings/camlia-ring', permanent: true },
    { source: '/product-category/:cat', destination: '/jewelry', permanent: true },
    { source: '/product-category/:cat/:subcat', destination: '/jewelry', permanent: true },
    { source: '/contact-2', destination: '/contact', permanent: true },
    { source: '/contact-2/', destination: '/contact', permanent: true },
    { source: '/news', destination: '/blog', permanent: true },
    { source: '/news/', destination: '/blog', permanent: true },
    { source: '/home', destination: '/', permanent: true },
    { source: '/home/', destination: '/', permanent: true },
    { source: '/terms-and-conditions', destination: '/terms', permanent: true },
    { source: '/terms-and-conditions/', destination: '/terms', permanent: true },
    { source: '/shipping-information', destination: '/terms', permanent: true },
    { source: '/shipping-information/', destination: '/terms', permanent: true },
    { source: '/returns-exchanges', destination: '/terms', permanent: true },
    { source: '/returns-exchanges/', destination: '/terms', permanent: true },
    { source: '/bez-ambar-store-locator1', destination: '/contact', permanent: true },
    { source: '/bez-ambar-store-locator1/', destination: '/contact', permanent: true },
    { source: '/case-studies', destination: '/about-bez-ambar', permanent: true },
    { source: '/case-studies/', destination: '/about-bez-ambar', permanent: true },
    // Top-20 WooCommerce legacy products — individual pages at /legacy/[slug]
    { source: '/shop/cosmic-fire-engagement-ring-fancy-yellow-radiant-cut', destination: '/legacy/cosmic-fire-engagement-ring-fancy-yellow-radiant-cut', permanent: true },
    { source: '/shop/cosmic-fire-engagement-ring-fancy-yellow-radiant-cut/', destination: '/legacy/cosmic-fire-engagement-ring-fancy-yellow-radiant-cut', permanent: true },
    { source: '/shop/a-baguette-diamond-eternity-band', destination: '/legacy/a-baguette-diamond-eternity-band', permanent: true },
    { source: '/shop/a-baguette-diamond-eternity-band/', destination: '/legacy/a-baguette-diamond-eternity-band', permanent: true },
    { source: '/shop/fancy-brown-diamond-frame-fire-ring-black-blaze', destination: '/legacy/fancy-brown-diamond-frame-fire-ring-black-blaze', permanent: true },
    { source: '/shop/fancy-brown-diamond-frame-fire-ring-black-blaze/', destination: '/legacy/fancy-brown-diamond-frame-fire-ring-black-blaze', permanent: true },
    { source: '/shop/stretchable-baguette-diamond-eternity-band', destination: '/legacy/stretchable-baguette-diamond-eternity-band', permanent: true },
    { source: '/shop/stretchable-baguette-diamond-eternity-band/', destination: '/legacy/stretchable-baguette-diamond-eternity-band', permanent: true },
    { source: '/shop/jacket-of-fire-diamond-stud-earrings', destination: '/legacy/jacket-of-fire-diamond-stud-earrings', permanent: true },
    { source: '/shop/jacket-of-fire-diamond-stud-earrings/', destination: '/legacy/jacket-of-fire-diamond-stud-earrings', permanent: true },
    { source: '/shop/20-carat-diamond-ring-from-bez-ambar', destination: '/legacy/20-carat-diamond-ring-from-bez-ambar', permanent: true },
    { source: '/shop/20-carat-diamond-ring-from-bez-ambar/', destination: '/legacy/20-carat-diamond-ring-from-bez-ambar', permanent: true },
    { source: '/shop/quadrillion-and-baguette-diamonds-wedding-band', destination: '/legacy/quadrillion-and-baguette-diamonds-wedding-band', permanent: true },
    { source: '/shop/quadrillion-and-baguette-diamonds-wedding-band/', destination: '/legacy/quadrillion-and-baguette-diamonds-wedding-band', permanent: true },
    { source: '/shop/tulip-trio-engagement-ring-round-diamonds', destination: '/legacy/tulip-trio-engagement-ring-round-diamonds', permanent: true },
    { source: '/shop/tulip-trio-engagement-ring-round-diamonds/', destination: '/legacy/tulip-trio-engagement-ring-round-diamonds', permanent: true },
    { source: '/shop/18k-white-gold-ring-fire-round-center', destination: '/legacy/18k-white-gold-ring-fire-round-center', permanent: true },
    { source: '/shop/18k-white-gold-ring-fire-round-center/', destination: '/legacy/18k-white-gold-ring-fire-round-center', permanent: true },
    { source: '/shop/confetti-melody-baguette-diamond-band', destination: '/legacy/confetti-melody-baguette-diamond-band', permanent: true },
    { source: '/shop/confetti-melody-baguette-diamond-band/', destination: '/legacy/confetti-melody-baguette-diamond-band', permanent: true },
    { source: '/shop/11-stone-15-carat-emerald-cut-diamond-wedding-band', destination: '/legacy/11-stone-15-carat-emerald-cut-diamond-wedding-band', permanent: true },
    { source: '/shop/11-stone-15-carat-emerald-cut-diamond-wedding-band/', destination: '/legacy/11-stone-15-carat-emerald-cut-diamond-wedding-band', permanent: true },
    { source: '/shop/5-carat-blue-diamond-pear-shape-engagement-ring', destination: '/legacy/5-carat-blue-diamond-pear-shape-engagement-ring', permanent: true },
    { source: '/shop/5-carat-blue-diamond-pear-shape-engagement-ring/', destination: '/legacy/5-carat-blue-diamond-pear-shape-engagement-ring', permanent: true },
    { source: '/shop/split-shank-ruby-and-diamond-engagement-ring', destination: '/legacy/split-shank-ruby-and-diamond-engagement-ring', permanent: true },
    { source: '/shop/split-shank-ruby-and-diamond-engagement-ring/', destination: '/legacy/split-shank-ruby-and-diamond-engagement-ring', permanent: true },
    { source: '/shop/8-carat-marquise-diamond-engagement-ring', destination: '/legacy/8-carat-marquise-diamond-engagement-ring', permanent: true },
    { source: '/shop/8-carat-marquise-diamond-engagement-ring/', destination: '/legacy/8-carat-marquise-diamond-engagement-ring', permanent: true },
    { source: '/shop/fancy-blue-diamond-cushion-cut-engagement-ring', destination: '/legacy/fancy-blue-diamond-cushion-cut-engagement-ring', permanent: true },
    { source: '/shop/fancy-blue-diamond-cushion-cut-engagement-ring/', destination: '/legacy/fancy-blue-diamond-cushion-cut-engagement-ring', permanent: true },
    { source: '/shop/20-carat-d-flawless-emerald-engagement-ring', destination: '/legacy/20-carat-d-flawless-emerald-engagement-ring', permanent: true },
    { source: '/shop/20-carat-d-flawless-emerald-engagement-ring/', destination: '/legacy/20-carat-d-flawless-emerald-engagement-ring', permanent: true },
    { source: '/shop/emerald-cut-diamond-and-emerald-baguette-three-stone-engagement-ring', destination: '/legacy/emerald-cut-diamond-and-emerald-baguette-three-stone-engagement-ring', permanent: true },
    { source: '/shop/emerald-cut-diamond-and-emerald-baguette-three-stone-engagement-ring/', destination: '/legacy/emerald-cut-diamond-and-emerald-baguette-three-stone-engagement-ring', permanent: true },
    { source: '/shop/three-stone-ring-emerald-center-trapezoids', destination: '/legacy/three-stone-ring-emerald-center-trapezoids', permanent: true },
    { source: '/shop/three-stone-ring-emerald-center-trapezoids/', destination: '/legacy/three-stone-ring-emerald-center-trapezoids', permanent: true },
    { source: '/shop/10-carat-radiant-pink-diamond-engagement-ring', destination: '/legacy/10-carat-radiant-pink-diamond-engagement-ring', permanent: true },
    { source: '/shop/10-carat-radiant-pink-diamond-engagement-ring/', destination: '/legacy/10-carat-radiant-pink-diamond-engagement-ring', permanent: true },
    // Three pieces formerly hand-built at /shop/ — migrated into the legacy template 2026-09-29
    { source: '/shop/ruby-flower-hug-earrings', destination: '/legacy/ruby-flower-hug-earrings', permanent: true },
    { source: '/shop/ruby-flower-hug-earrings/', destination: '/legacy/ruby-flower-hug-earrings', permanent: true },
    { source: '/shop/maharajah-ring-with-red-and-green-diamonds', destination: '/legacy/maharajah-ring-with-red-and-green-diamonds', permanent: true },
    { source: '/shop/maharajah-ring-with-red-and-green-diamonds/', destination: '/legacy/maharajah-ring-with-red-and-green-diamonds', permanent: true },
    { source: '/shop/3-stone-oval-engagement-ring-with-blaze', destination: '/legacy/3-stone-oval-engagement-ring-with-blaze', permanent: true },
    { source: '/shop/3-stone-oval-engagement-ring-with-blaze/', destination: '/legacy/3-stone-oval-engagement-ring-with-blaze', permanent: true },
    // Everything else under /shop/ goes to the archive
    { source: '/shop/:slug', destination: '/archive', permanent: true },
    { source: '/shop/:slug/', destination: '/archive', permanent: true },
    { source: '/designer-diamond-rings-bez-ambars-finest-engagement-rings', destination: '/blog', permanent: true },
    { source: '/designer-diamond-rings-bez-ambars-finest-engagement-rings/', destination: '/blog', permanent: true },
    { source: '/blaze-cut-diamonds-unmatched-engagement-rings-wedding-bands', destination: '/blog/blaze-cut-diamond', permanent: true },
    { source: '/blaze-cut-diamonds-unmatched-engagement-rings-wedding-bands/', destination: '/blog/blaze-cut-diamond', permanent: true },
    { source: '/design-your-own-diamond-ring-wedding-engagement', destination: '/blog', permanent: true },
    { source: '/design-your-own-diamond-ring-wedding-engagement/', destination: '/blog', permanent: true },
    { source: '/custom-rings-master-craftsman-create-dream-wedding-ring', destination: '/blog', permanent: true },
    { source: '/custom-rings-master-craftsman-create-dream-wedding-ring/', destination: '/blog', permanent: true },
    { source: '/ultimate-wedding-planning-checklist-monthly-breakdown', destination: '/blog', permanent: true },
    { source: '/ultimate-wedding-planning-checklist-monthly-breakdown/', destination: '/blog', permanent: true },
    { source: '/best-diamond-cut-choosing-perfect-diamonds', destination: '/blog/ideal-cut-diamond-explained', permanent: true },
    { source: '/best-diamond-cut-choosing-perfect-diamonds/', destination: '/blog/ideal-cut-diamond-explained', permanent: true },
    { source: '/womens-diamond-engagement-rings', destination: '/blog', permanent: true },
    { source: '/womens-diamond-engagement-rings/', destination: '/blog', permanent: true },
    { source: '/wedding-bands-stunning-fine-jewelry-his-hers', destination: '/blog', permanent: true },
    { source: '/wedding-bands-stunning-fine-jewelry-his-hers/', destination: '/blog', permanent: true },
    { source: '/bridal-ring-sets-diamond-wedding-ring-sets', destination: '/blog', permanent: true },
    { source: '/bridal-ring-sets-diamond-wedding-ring-sets/', destination: '/blog', permanent: true },
    { source: '/wedding-planning-30-experts-tips-tricks-theknot-com', destination: '/blog', permanent: true },
    { source: '/wedding-planning-30-experts-tips-tricks-theknot-com/', destination: '/blog', permanent: true },
    { source: '/choose-engagement-ring-cut-setting-metal', destination: '/blog', permanent: true },
    { source: '/choose-engagement-ring-cut-setting-metal/', destination: '/blog', permanent: true },
    { source: '/wedding-engagement-rings-1st-time-buyers-guide', destination: '/blog', permanent: true },
    { source: '/wedding-engagement-rings-1st-time-buyers-guide/', destination: '/blog', permanent: true },
    { source: '/bez-ambar-unique-buying-experience-los-angeles', destination: '/blog', permanent: true },
    { source: '/bez-ambar-unique-buying-experience-los-angeles/', destination: '/blog', permanent: true },
    { source: '/sets-apart-designer-jewelry-rest', destination: '/blog', permanent: true },
    { source: '/sets-apart-designer-jewelry-rest/', destination: '/blog', permanent: true },
    { source: '/designer-engagement-rings-bez-ambar', destination: '/blog', permanent: true },
    { source: '/designer-engagement-rings-bez-ambar/', destination: '/blog', permanent: true },
    { source: '/custom-rings-diamonds-gemstones', destination: '/blog', permanent: true },
    { source: '/custom-rings-diamonds-gemstones/', destination: '/blog', permanent: true },
    { source: '/fine-jewelry-stunning-necklaces-bracelets-earrings', destination: '/blog', permanent: true },
    { source: '/fine-jewelry-stunning-necklaces-bracelets-earrings/', destination: '/blog', permanent: true },
    { source: '/knife-edge-unique-wedding-rings', destination: '/blog', permanent: true },
    { source: '/knife-edge-unique-wedding-rings/', destination: '/blog', permanent: true },
    { source: '/amethyst-engagement-rings', destination: '/blog/amethyst-jewelry-buying-guide', permanent: true },
    { source: '/amethyst-engagement-rings/', destination: '/blog/amethyst-jewelry-buying-guide', permanent: true },
    { source: '/unique-diamond-jewelry-los-angeles-ca', destination: '/blog', permanent: true },
    { source: '/unique-diamond-jewelry-los-angeles-ca/', destination: '/blog', permanent: true },
    { source: '/propose-to-partner-perfect-rings', destination: '/blog', permanent: true },
    { source: '/propose-to-partner-perfect-rings/', destination: '/blog', permanent: true },
    { source: '/ruby-engagement-rings-custom-red-rubies-diamonds', destination: '/blog', permanent: true },
    { source: '/ruby-engagement-rings-custom-red-rubies-diamonds/', destination: '/blog', permanent: true },
    { source: '/anniversary-rings-wedding-rings-eternity-rings', destination: '/blog/anniversary-rings-wedding-rings-eternity-rings', permanent: true },
    { source: '/anniversary-rings-wedding-rings-eternity-rings/', destination: '/blog/anniversary-rings-wedding-rings-eternity-rings', permanent: true },
    { source: '/wedding-bands-for-women-eternity-rings', destination: '/blog', permanent: true },
    { source: '/wedding-bands-for-women-eternity-rings/', destination: '/blog', permanent: true },
    { source: '/custom-jewelry-gold-jewelry', destination: '/blog', permanent: true },
    { source: '/custom-jewelry-gold-jewelry/', destination: '/blog', permanent: true },
    { source: '/custom-diamond-necklace-designed-master-craftsmen', destination: '/blog', permanent: true },
    { source: '/custom-diamond-necklace-designed-master-craftsmen/', destination: '/blog', permanent: true },
    { source: '/bracelets-stunning-diamond-bracelet-designs', destination: '/blog', permanent: true },
    { source: '/bracelets-stunning-diamond-bracelet-designs/', destination: '/blog', permanent: true },
    { source: '/jewelry-care-cleaning-jewelry', destination: '/blog/fine-jewelry-care-and-maintenance', permanent: true },
    { source: '/jewelry-care-cleaning-jewelry/', destination: '/blog/fine-jewelry-care-and-maintenance', permanent: true },
    { source: '/princess-cut-diamond-inventor', destination: '/blog/princess-cut-diamond-inventor', permanent: true },
    { source: '/princess-cut-diamond-inventor/', destination: '/blog/princess-cut-diamond-inventor', permanent: true },
    { source: '/gemstone-jewelry-emerald-engagement-rings', destination: '/blog/should-you-buy-emerald-engagement-rings', permanent: true },
    { source: '/gemstone-jewelry-emerald-engagement-rings/', destination: '/blog/should-you-buy-emerald-engagement-rings', permanent: true },
    { source: '/radiant-cushion-cut-engagement-rings', destination: '/blog', permanent: true },
    { source: '/radiant-cushion-cut-engagement-rings/', destination: '/blog', permanent: true },
    { source: '/diamond-rings-wedding-rings', destination: '/blog', permanent: true },
    { source: '/diamond-rings-wedding-rings/', destination: '/blog', permanent: true },
    { source: '/designer-diamond-engagement-rings', destination: '/blog', permanent: true },
    { source: '/designer-diamond-engagement-rings/', destination: '/blog', permanent: true },
    { source: '/halo-engagement-ring-designer-diamond-rings', destination: '/blog/halo-ring-setting', permanent: true },
    { source: '/halo-engagement-ring-designer-diamond-rings/', destination: '/blog/halo-ring-setting', permanent: true },
    { source: '/designer-engagement-rings-wedding-bands', destination: '/blog', permanent: true },
    { source: '/designer-engagement-rings-wedding-bands/', destination: '/blog', permanent: true },
    { source: '/finest-designer-engagement-rings', destination: '/blog', permanent: true },
    { source: '/finest-designer-engagement-rings/', destination: '/blog', permanent: true },
    { source: '/designer-split-shank-engagement-rings', destination: '/blog/split-shank-engagement-ring', permanent: true },
    { source: '/designer-split-shank-engagement-rings/', destination: '/blog/split-shank-engagement-ring', permanent: true },
    { source: '/authentic-bez-ambar-buyer-beware', destination: '/blog/authentic-bez-ambar-buyer-beware', permanent: true },
    { source: '/authentic-bez-ambar-buyer-beware/', destination: '/blog/authentic-bez-ambar-buyer-beware', permanent: true },
    { source: '/unique-heart-shaped-engagement-rings-bez-ambar', destination: '/blog/heart-shaped-diamond-ring', permanent: true },
    { source: '/unique-heart-shaped-engagement-rings-bez-ambar/', destination: '/blog/heart-shaped-diamond-ring', permanent: true },
    { source: '/designer-engagement-rings-chicago', destination: '/blog', permanent: true },
    { source: '/designer-engagement-rings-chicago/', destination: '/blog', permanent: true },
    { source: '/designer-engagement-rings-nashville-tn', destination: '/blog', permanent: true },
    { source: '/designer-engagement-rings-nashville-tn/', destination: '/blog', permanent: true },
    { source: '/what-is-a-halo-engagement-ring', destination: '/blog/halo-ring-setting', permanent: true },
    { source: '/what-is-a-halo-engagement-ring/', destination: '/blog/halo-ring-setting', permanent: true },
    { source: '/engagement-rings-boston', destination: '/blog', permanent: true },
    { source: '/engagement-rings-boston/', destination: '/blog', permanent: true },
    { source: '/designer-engagement-rings-dallas', destination: '/blog', permanent: true },
    { source: '/designer-engagement-rings-dallas/', destination: '/blog', permanent: true },
    { source: '/engagement-rings-houston', destination: '/blog', permanent: true },
    { source: '/engagement-rings-houston/', destination: '/blog', permanent: true },
    { source: '/shop-fine-jewelry-online-store', destination: '/blog/online-jewelry-stores', permanent: true },
    { source: '/shop-fine-jewelry-online-store/', destination: '/blog/online-jewelry-stores', permanent: true },
    { source: '/engagement-rings-los-angeles-best-jewelry', destination: '/blog', permanent: true },
    { source: '/engagement-rings-los-angeles-best-jewelry/', destination: '/blog', permanent: true },
    { source: '/white-black-diamond-jewelry', destination: '/blog/black-diamond-jewelry', permanent: true },
    { source: '/white-black-diamond-jewelry/', destination: '/blog/black-diamond-jewelry', permanent: true },
    { source: '/designer-jewelry-2015-golden-globes', destination: '/blog', permanent: true },
    { source: '/designer-jewelry-2015-golden-globes/', destination: '/blog', permanent: true },
    { source: '/men-women-really-want-valentines-day', destination: '/blog', permanent: true },
    { source: '/men-women-really-want-valentines-day/', destination: '/blog', permanent: true },
    { source: '/comparison-video-blaze-cut-diamond-vs-cuts', destination: '/blog/blaze-cut-diamond', permanent: true },
    { source: '/comparison-video-blaze-cut-diamond-vs-cuts/', destination: '/blog/blaze-cut-diamond', permanent: true },
    { source: '/difference-yellow-gold-white-gold-rose-gold', destination: '/blog', permanent: true },
    { source: '/difference-yellow-gold-white-gold-rose-gold/', destination: '/blog', permanent: true },
    { source: '/stackable-rings-bez-ambar', destination: '/blog', permanent: true },
    { source: '/stackable-rings-bez-ambar/', destination: '/blog', permanent: true },
    { source: '/are-split-shank-engagement-rings-popular', destination: '/blog/split-shank-engagement-ring', permanent: true },
    { source: '/are-split-shank-engagement-rings-popular/', destination: '/blog/split-shank-engagement-ring', permanent: true },
    { source: '/bez-ambars-ring-enhancers-bookend-bands', destination: '/blog', permanent: true },
    { source: '/bez-ambars-ring-enhancers-bookend-bands/', destination: '/blog', permanent: true },
    { source: '/fancy-yellow-heart-shape-diamond-with-blaze', destination: '/blog/blaze-cut-diamond', permanent: true },
    { source: '/fancy-yellow-heart-shape-diamond-with-blaze/', destination: '/blog/blaze-cut-diamond', permanent: true },
    { source: '/three-stone-engagement-ring-princess-cut', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/three-stone-engagement-ring-princess-cut/', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/three-stone-engagement-ring-with-oval-and-blaze', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/three-stone-engagement-ring-with-oval-and-blaze/', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/three-stone-engagement-ring-oval-cut', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/three-stone-engagement-ring-oval-cut/', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/bamboo-engagement-ring-with-blaze', destination: '/blog', permanent: true },
    { source: '/bamboo-engagement-ring-with-blaze/', destination: '/blog', permanent: true },
    { source: '/round-center-with-square-sapphires', destination: '/blog', permanent: true },
    { source: '/round-center-with-square-sapphires/', destination: '/blog', permanent: true },
    { source: '/round-center-with-square-rubies', destination: '/blog', permanent: true },
    { source: '/round-center-with-square-rubies/', destination: '/blog', permanent: true },
    { source: '/three-stones-engagement-ring-for-emerald', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/three-stones-engagement-ring-for-emerald/', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/three-stones-engagement-ring-for-princess-cut-diamonds-with-blaze', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/three-stones-engagement-ring-for-princess-cut-diamonds-with-blaze/', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/pave-split-shank-engagement-ring-with-octagon-halo', destination: '/blog/split-shank-engagement-ring', permanent: true },
    { source: '/pave-split-shank-engagement-ring-with-octagon-halo/', destination: '/blog/split-shank-engagement-ring', permanent: true },
    { source: '/one-carat-heart-shaped-diamond-ring', destination: '/blog/heart-shaped-diamond-ring', permanent: true },
    { source: '/one-carat-heart-shaped-diamond-ring/', destination: '/blog/heart-shaped-diamond-ring', permanent: true },
    { source: '/mens-unique-wedding-rings', destination: '/blog', permanent: true },
    { source: '/mens-unique-wedding-rings/', destination: '/blog', permanent: true },
    { source: '/radiant-cut-diamond-band', destination: '/blog/radiant-cut-diamond-engagement-ring', permanent: true },
    { source: '/radiant-cut-diamond-band/', destination: '/blog/radiant-cut-diamond-engagement-ring', permanent: true },
    { source: '/three-stone-ring-meaning', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/three-stone-ring-meaning/', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/cushion-cut-diamond-engagement-ring', destination: '/blog/cushion-cut-diamond-engagement-ring', permanent: true },
    { source: '/cushion-cut-diamond-engagement-ring/', destination: '/blog/cushion-cut-diamond-engagement-ring', permanent: true },
    { source: '/princess-cut-diamond-rings', destination: '/blog/princess-cut-diamond-ring-guide', permanent: true },
    { source: '/princess-cut-diamond-rings/', destination: '/blog/princess-cut-diamond-ring-guide', permanent: true },
    { source: '/heart-diamond-engagement-ring', destination: '/blog/heart-shaped-diamond-ring', permanent: true },
    { source: '/heart-diamond-engagement-ring/', destination: '/blog/heart-shaped-diamond-ring', permanent: true },
    { source: '/engagement-rings-diamonds-sapphires', destination: '/blog/sapphire-engagement-rings-yes-no', permanent: true },
    { source: '/engagement-rings-diamonds-sapphires/', destination: '/blog/sapphire-engagement-rings-yes-no', permanent: true },
    { source: '/pink-princess-cut-diamonds', destination: '/blog/is-a-pink-diamond-engagement-ring-right-for-you', permanent: true },
    { source: '/pink-princess-cut-diamonds/', destination: '/blog/is-a-pink-diamond-engagement-ring-right-for-you', permanent: true },
    { source: '/custom-designer-jewelry-bez-ambar', destination: '/blog/custom-jewelry-design-process', permanent: true },
    { source: '/custom-designer-jewelry-bez-ambar/', destination: '/blog/custom-jewelry-design-process', permanent: true },
    { source: '/jewelers-in-shreveport-la', destination: '/retailers/sid-potts', permanent: true },
    { source: '/jewelers-in-shreveport-la/', destination: '/retailers/sid-potts', permanent: true },
    { source: '/what-is-cathedral-engagement-ring-setting', destination: '/blog', permanent: true },
    { source: '/what-is-cathedral-engagement-ring-setting/', destination: '/blog', permanent: true },
    { source: '/los-angeles-custom-jewelry-designer-jewelry-store', destination: '/contact', permanent: true },
    { source: '/los-angeles-custom-jewelry-designer-jewelry-store/', destination: '/contact', permanent: true },
    { source: '/designer-diamond-engagement-ring', destination: '/blog', permanent: true },
    { source: '/designer-diamond-engagement-ring/', destination: '/blog', permanent: true },
    { source: '/women-three-stone-rings', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/women-three-stone-rings/', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/princess-cut-ring', destination: '/blog/princess-cut-diamond-ring-guide', permanent: true },
    { source: '/princess-cut-ring/', destination: '/blog/princess-cut-diamond-ring-guide', permanent: true },
    { source: '/wide-band-diamond-rings', destination: '/blog', permanent: true },
    { source: '/wide-band-diamond-rings/', destination: '/blog', permanent: true },
    { source: '/emerald-cut-diamond-earrings', destination: '/blog', permanent: true },
    { source: '/emerald-cut-diamond-earrings/', destination: '/blog', permanent: true },
    { source: '/why-is-it-important-to-take-care-of-diamond-jewelry', destination: '/blog/fine-jewelry-care-and-maintenance', permanent: true },
    { source: '/why-is-it-important-to-take-care-of-diamond-jewelry/', destination: '/blog/fine-jewelry-care-and-maintenance', permanent: true },
    { source: '/5-carat-diamond-ring', destination: '/blog/5-carat-diamond-ring', permanent: true },
    { source: '/5-carat-diamond-ring/', destination: '/blog/5-carat-diamond-ring', permanent: true },
    { source: '/what-to-do-with-a-chipped-diamond', destination: '/blog/what-to-do-with-a-chipped-diamond', permanent: true },
    { source: '/what-to-do-with-a-chipped-diamond/', destination: '/blog/what-to-do-with-a-chipped-diamond', permanent: true },
    { source: '/yellow-gold-cross-necklace', destination: '/blog', permanent: true },
    { source: '/yellow-gold-cross-necklace/', destination: '/blog', permanent: true },
    { source: '/quadrillion-cut-different-princess-cut', destination: '/blog/quadrillion-cut-different-princess-cut', permanent: true },
    { source: '/quadrillion-cut-different-princess-cut/', destination: '/blog/quadrillion-cut-different-princess-cut', permanent: true },
    { source: '/pink-diamond-engagement-rings', destination: '/blog/is-a-pink-diamond-engagement-ring-right-for-you', permanent: true },
    { source: '/pink-diamond-engagement-rings/', destination: '/blog/is-a-pink-diamond-engagement-ring-right-for-you', permanent: true },
    { source: '/customized-engagement-ring-for-a-special-order', destination: '/blog', permanent: true },
    { source: '/customized-engagement-ring-for-a-special-order/', destination: '/blog', permanent: true },
    { source: '/all-around-stag-bands', destination: '/blog', permanent: true },
    { source: '/all-around-stag-bands/', destination: '/blog', permanent: true },
    { source: '/engagement-rings-with-bands', destination: '/blog', permanent: true },
    { source: '/engagement-rings-with-bands/', destination: '/blog', permanent: true },
    { source: '/unique-engagement-ring-settings', destination: '/blog', permanent: true },
    { source: '/unique-engagement-ring-settings/', destination: '/blog', permanent: true },
    { source: '/round-brilliant-cut-diamonds-vs-future-round-diamonds', destination: '/blog/round-brilliant-cut-diamond-ring', permanent: true },
    { source: '/round-brilliant-cut-diamonds-vs-future-round-diamonds/', destination: '/blog/round-brilliant-cut-diamond-ring', permanent: true },
    { source: '/bez-ambars-new-patented-design-divine-cut-diamond', destination: '/blog/bez-ambars-new-patented-design-divine-cut-diamond', permanent: true },
    { source: '/bez-ambars-new-patented-design-divine-cut-diamond/', destination: '/blog/bez-ambars-new-patented-design-divine-cut-diamond', permanent: true },
    { source: '/micro-pave-heart-pendant-accent-diamond-ring', destination: '/blog', permanent: true },
    { source: '/micro-pave-heart-pendant-accent-diamond-ring/', destination: '/blog', permanent: true },
    { source: '/blaze-cut-diamond', destination: '/blog/blaze-cut-diamond', permanent: true },
    { source: '/blaze-cut-diamond/', destination: '/blog/blaze-cut-diamond', permanent: true },
    { source: '/genesis-diamonds-nashville', destination: '/blog', permanent: true },
    { source: '/genesis-diamonds-nashville/', destination: '/blog', permanent: true },
    { source: '/fancy-yellow-diamond-engagement-rings', destination: '/blog/fancy-yellow-diamond-rings', permanent: true },
    { source: '/fancy-yellow-diamond-engagement-rings/', destination: '/blog/fancy-yellow-diamond-rings', permanent: true },
    { source: '/royal-jewelers-andover', destination: '/retailers/royal-jewelers-andover', permanent: true },
    { source: '/royal-jewelers-andover/', destination: '/retailers/royal-jewelers-andover', permanent: true },
    { source: '/invisible-setting-for-diamonds-a-bez-ambar-innovation', destination: '/blog/invisible-setting-for-diamonds-a-bez-ambar-innovation', permanent: true },
    { source: '/invisible-setting-for-diamonds-a-bez-ambar-innovation/', destination: '/blog/invisible-setting-for-diamonds-a-bez-ambar-innovation', permanent: true },
    { source: '/sid-potts-shreveport', destination: '/retailers/sid-potts', permanent: true },
    { source: '/sid-potts-shreveport/', destination: '/retailers/sid-potts', permanent: true },
    { source: '/maurice-badler-fine-jewelry', destination: '/blog', permanent: true },
    { source: '/maurice-badler-fine-jewelry/', destination: '/blog', permanent: true },
    { source: '/badler-last-call', destination: '/blog', permanent: true },
    { source: '/badler-last-call/', destination: '/blog', permanent: true },
    { source: '/edmund-t-ahee-jewelers', destination: '/retailers/ahee-jewelers', permanent: true },
    { source: '/edmund-t-ahee-jewelers/', destination: '/retailers/ahee-jewelers', permanent: true },
    { source: '/sid-potts', destination: '/retailers/sid-potts', permanent: true },
    { source: '/sid-potts/', destination: '/retailers/sid-potts', permanent: true },
    { source: '/edmund-ahee-jewelers', destination: '/retailers/ahee-jewelers', permanent: true },
    { source: '/edmund-ahee-jewelers/', destination: '/retailers/ahee-jewelers', permanent: true },
    { source: '/ahee-jewelers', destination: '/retailers/ahee-jewelers', permanent: true },
    { source: '/ahee-jewelers/', destination: '/retailers/ahee-jewelers', permanent: true },
    { source: '/eiseman-jewels', destination: '/retailers/eiseman-jewels', permanent: true },
    { source: '/eiseman-jewels/', destination: '/retailers/eiseman-jewels', permanent: true },
    { source: '/eiseman-jewelers-dallas-tx', destination: '/retailers/eiseman-jewels', permanent: true },
    { source: '/eiseman-jewelers-dallas-tx/', destination: '/retailers/eiseman-jewels', permanent: true },
    { source: '/kassab-jewelers-portland', destination: '/retailers/kassab-jewelers', permanent: true },
    { source: '/kassab-jewelers-portland/', destination: '/retailers/kassab-jewelers', permanent: true },
    { source: '/kassab-jewelers', destination: '/retailers/kassab-jewelers', permanent: true },
    { source: '/kassab-jewelers/', destination: '/retailers/kassab-jewelers', permanent: true },
    { source: '/james-elliott-jewelers', destination: '/retailers/james-elliott-jewelers', permanent: true },
    { source: '/james-elliott-jewelers/', destination: '/retailers/james-elliott-jewelers', permanent: true },
    { source: '/james-elliott-scottsdale', destination: '/retailers/james-elliott-jewelers', permanent: true },
    { source: '/james-elliott-scottsdale/', destination: '/retailers/james-elliott-jewelers', permanent: true },
    { source: '/alsonjewelers-com', destination: '/retailers/alson-jewelers', permanent: true },
    { source: '/alsonjewelers-com/', destination: '/retailers/alson-jewelers', permanent: true },
    { source: '/turgeon-raine', destination: '/blog', permanent: true },
    { source: '/turgeon-raine/', destination: '/blog', permanent: true },
    { source: '/turgeon-raine-seattle', destination: '/blog', permanent: true },
    { source: '/turgeon-raine-seattle/', destination: '/blog', permanent: true },
    { source: '/alson-jewelers', destination: '/retailers/alson-jewelers', permanent: true },
    { source: '/alson-jewelers/', destination: '/retailers/alson-jewelers', permanent: true },
    { source: '/alson-jewelry', destination: '/retailers/alson-jewelers', permanent: true },
    { source: '/alson-jewelry/', destination: '/retailers/alson-jewelers', permanent: true },
    { source: '/engagement-rings-and-wedding-bands-buying-online-or-in-store', destination: '/blog/online-jewelry-stores', permanent: true },
    { source: '/engagement-rings-and-wedding-bands-buying-online-or-in-store/', destination: '/blog/online-jewelry-stores', permanent: true },
    { source: '/alson-jewelers-cleveland-oh', destination: '/retailers/alson-jewelers', permanent: true },
    { source: '/alson-jewelers-cleveland-oh/', destination: '/retailers/alson-jewelers', permanent: true },
    { source: '/bigham-jewelers', destination: '/retailers/bigham-jewelers', permanent: true },
    { source: '/bigham-jewelers/', destination: '/retailers/bigham-jewelers', permanent: true },
    { source: '/international-diamond-center-savannah-ga', destination: '/blog', permanent: true },
    { source: '/international-diamond-center-savannah-ga/', destination: '/blog', permanent: true },
    { source: '/international-diamond-center-orlando', destination: '/blog', permanent: true },
    { source: '/international-diamond-center-orlando/', destination: '/blog', permanent: true },
    { source: '/international-diamond-center-clearwater', destination: '/blog', permanent: true },
    { source: '/international-diamond-center-clearwater/', destination: '/blog', permanent: true },
    { source: '/international-diamond-center-tampa', destination: '/blog', permanent: true },
    { source: '/international-diamond-center-tampa/', destination: '/blog', permanent: true },
    { source: '/international-diamond-center-altamonte-springs', destination: '/blog', permanent: true },
    { source: '/international-diamond-center-altamonte-springs/', destination: '/blog', permanent: true },
    { source: '/international-diamond-center', destination: '/blog', permanent: true },
    { source: '/international-diamond-center/', destination: '/blog', permanent: true },
    { source: '/international-diamond-center-winter-park-fl', destination: '/blog', permanent: true },
    { source: '/international-diamond-center-winter-park-fl/', destination: '/blog', permanent: true },
    { source: '/ascot-diamondsarlington-va', destination: '/retailers/ascot-diamonds', permanent: true },
    { source: '/ascot-diamondsarlington-va/', destination: '/retailers/ascot-diamonds', permanent: true },
    { source: '/ascot-diamonds', destination: '/retailers/ascot-diamonds', permanent: true },
    { source: '/ascot-diamonds/', destination: '/retailers/ascot-diamonds', permanent: true },
    { source: '/ascot-diamonds-dallas-tx', destination: '/retailers/ascot-diamonds', permanent: true },
    { source: '/ascot-diamonds-dallas-tx/', destination: '/retailers/ascot-diamonds', permanent: true },
    { source: '/ascot-jewelers', destination: '/retailers/ascot-diamonds', permanent: true },
    { source: '/ascot-jewelers/', destination: '/retailers/ascot-diamonds', permanent: true },
    { source: '/i-gorman-jewelers', destination: '/retailers/i-gorman-jewelers', permanent: true },
    { source: '/i-gorman-jewelers/', destination: '/retailers/i-gorman-jewelers', permanent: true },
    { source: '/t-bird-jewelers', destination: '/retailers/t-bird-jewelers', permanent: true },
    { source: '/t-bird-jewelers/', destination: '/retailers/t-bird-jewelers', permanent: true },
    { source: '/t-bird-jewels', destination: '/retailers/t-bird-jewelers', permanent: true },
    { source: '/t-bird-jewels/', destination: '/retailers/t-bird-jewelers', permanent: true },
    { source: '/t-bird-jewelry', destination: '/retailers/t-bird-jewelers', permanent: true },
    { source: '/t-bird-jewelry/', destination: '/retailers/t-bird-jewelers', permanent: true },
    { source: '/fred-brown-jewelers-com', destination: '/contact', permanent: true },
    { source: '/fred-brown-jewelers-com/', destination: '/contact', permanent: true },
    { source: '/radcliffe-pikesville', destination: '/retailers/radcliffe-jewelers', permanent: true },
    { source: '/radcliffe-pikesville/', destination: '/retailers/radcliffe-jewelers', permanent: true },
    { source: '/radcliffe-jewelers', destination: '/retailers/radcliffe-jewelers', permanent: true },
    { source: '/radcliffe-jewelers/', destination: '/retailers/radcliffe-jewelers', permanent: true },
    { source: '/radcliffe-baltimore', destination: '/retailers/radcliffe-jewelers', permanent: true },
    { source: '/radcliffe-baltimore/', destination: '/retailers/radcliffe-jewelers', permanent: true },
    { source: '/radcliffe-maryland', destination: '/retailers/radcliffe-jewelers', permanent: true },
    { source: '/radcliffe-maryland/', destination: '/retailers/radcliffe-jewelers', permanent: true },
    { source: '/difference-between-platinum-and-white-gold', destination: '/blog/platinum-vs-white-gold-complete-guide', permanent: true },
    { source: '/difference-between-platinum-and-white-gold/', destination: '/blog/platinum-vs-white-gold-complete-guide', permanent: true },
    { source: '/titanium-rings-men-pros-and-cons', destination: '/blog/titanium-rings-men-pros-and-cons', permanent: true },
    { source: '/titanium-rings-men-pros-and-cons/', destination: '/blog/titanium-rings-men-pros-and-cons', permanent: true },
    { source: '/radcliffe-towson', destination: '/retailers/radcliffe-jewelers', permanent: true },
    { source: '/radcliffe-towson/', destination: '/retailers/radcliffe-jewelers', permanent: true },
    { source: '/diamonds-made-valued', destination: '/blog', permanent: true },
    { source: '/diamonds-made-valued/', destination: '/blog', permanent: true },
    { source: '/stay-within-budget-buy-dream-ring', destination: '/blog', permanent: true },
    { source: '/stay-within-budget-buy-dream-ring/', destination: '/blog', permanent: true },
    { source: '/london-jewelers-long-island', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/london-jewelers-long-island/', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/london-jewelers-new-york', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/london-jewelers-new-york/', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/london-jewelers-americana-manhasset', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/london-jewelers-americana-manhasset/', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/london-jewelers-manhasset', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/london-jewelers-manhasset/', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/london-jewelers-east-hampton', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/london-jewelers-east-hampton/', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/london-jewelers-south-hampton', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/london-jewelers-south-hampton/', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/vintage-solitaire-engagement-rings', destination: '/blog/vintage-antique-engagement-rings', permanent: true },
    { source: '/vintage-solitaire-engagement-rings/', destination: '/blog/vintage-antique-engagement-rings', permanent: true },
    { source: '/london-jewelers-glen-cove', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/london-jewelers-glen-cove/', destination: '/retailers/london-jewelers-long-island', permanent: true },
    { source: '/the-blake-lively-inspired-engagement-ring', destination: '/blog', permanent: true },
    { source: '/the-blake-lively-inspired-engagement-ring/', destination: '/blog', permanent: true },
    { source: '/men-wedding-ring-buying-guide', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/men-wedding-ring-buying-guide/', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/birthstones-month-gemstones-and-engagement-rings', destination: '/blog', permanent: true },
    { source: '/birthstones-month-gemstones-and-engagement-rings/', destination: '/blog', permanent: true },
    { source: '/10-largest-diamonds-ever-found', destination: '/blog', permanent: true },
    { source: '/10-largest-diamonds-ever-found/', destination: '/blog', permanent: true },
    { source: '/the-significance-of-mens-wedding-bands', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/the-significance-of-mens-wedding-bands/', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/natural-pink-sapphire-earrings', destination: '/blog', permanent: true },
    { source: '/natural-pink-sapphire-earrings/', destination: '/blog', permanent: true },
    { source: '/perfect-men-wedding-bands-diamonds-guidance', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/perfect-men-wedding-bands-diamonds-guidance/', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/black-diamond-earrings-women', destination: '/blog/black-diamond-jewelry', permanent: true },
    { source: '/black-diamond-earrings-women/', destination: '/blog/black-diamond-jewelry', permanent: true },
    { source: '/ring-of-light', destination: '/blog', permanent: true },
    { source: '/ring-of-light/', destination: '/blog', permanent: true },
    { source: '/handmade-jewelry-designs', destination: '/blog', permanent: true },
    { source: '/handmade-jewelry-designs/', destination: '/blog', permanent: true },
    { source: '/blaze-halo-setting-makes-diamond-look-bigger', destination: '/blog/blaze-halo-setting-makes-diamond-look-bigger', permanent: true },
    { source: '/blaze-halo-setting-makes-diamond-look-bigger/', destination: '/blog/blaze-halo-setting-makes-diamond-look-bigger', permanent: true },
    { source: '/custom-ring-fire-fancy-yellow-diamond', destination: '/blog/fancy-yellow-diamond-rings', permanent: true },
    { source: '/custom-ring-fire-fancy-yellow-diamond/', destination: '/blog/fancy-yellow-diamond-rings', permanent: true },
    { source: '/marquise-engagement-rings', destination: '/blog/marquise-cut-diamond-engagement-ring', permanent: true },
    { source: '/marquise-engagement-rings/', destination: '/blog/marquise-cut-diamond-engagement-ring', permanent: true },
    { source: '/custom-three-row-wedding-bands-for-women', destination: '/blog', permanent: true },
    { source: '/custom-three-row-wedding-bands-for-women/', destination: '/blog', permanent: true },
    { source: '/heart-shaped-silvet-ring-with-rubies', destination: '/blog', permanent: true },
    { source: '/heart-shaped-silvet-ring-with-rubies/', destination: '/blog', permanent: true },
    { source: '/blue-diamond-pear-shape-ring', destination: '/blog/blue-diamond-rings', permanent: true },
    { source: '/blue-diamond-pear-shape-ring/', destination: '/blog/blue-diamond-rings', permanent: true },
    { source: '/cushion-cut-engagement-rings', destination: '/blog/cushion-cut-diamond-engagement-ring', permanent: true },
    { source: '/cushion-cut-engagement-rings/', destination: '/blog/cushion-cut-diamond-engagement-ring', permanent: true },
    { source: '/dancing-with-the-stars', destination: '/blog', permanent: true },
    { source: '/dancing-with-the-stars/', destination: '/blog', permanent: true },
    { source: '/ella-full-finger-ring', destination: '/blog', permanent: true },
    { source: '/ella-full-finger-ring/', destination: '/blog', permanent: true },
    { source: '/what-is-a-wedding-band', destination: '/blog', permanent: true },
    { source: '/what-is-a-wedding-band/', destination: '/blog', permanent: true },
    { source: '/blue-pasha-custom-tanzanite-engagement-rings', destination: '/blog/tanzanite-jewelry-guide', permanent: true },
    { source: '/blue-pasha-custom-tanzanite-engagement-rings/', destination: '/blog/tanzanite-jewelry-guide', permanent: true },
    { source: '/wedding-ring-designs', destination: '/blog', permanent: true },
    { source: '/wedding-ring-designs/', destination: '/blog', permanent: true },
    { source: '/what-is-a-wedding-anniversary-ring', destination: '/blog/anniversary-rings-wedding-rings-eternity-rings', permanent: true },
    { source: '/what-is-a-wedding-anniversary-ring/', destination: '/blog/anniversary-rings-wedding-rings-eternity-rings', permanent: true },
    { source: '/halo-ring-setting', destination: '/blog/halo-ring-setting', permanent: true },
    { source: '/halo-ring-setting/', destination: '/blog/halo-ring-setting', permanent: true },
    { source: '/pink-diamond-engagement-rings-2', destination: '/blog/is-a-pink-diamond-engagement-ring-right-for-you', permanent: true },
    { source: '/pink-diamond-engagement-rings-2/', destination: '/blog/is-a-pink-diamond-engagement-ring-right-for-you', permanent: true },
    { source: '/ring-size-guide-choosing-ring-size', destination: '/blog/ring-size-guide-choosing-ring-size', permanent: true },
    { source: '/ring-size-guide-choosing-ring-size/', destination: '/blog/ring-size-guide-choosing-ring-size', permanent: true },
    { source: '/blue-sapphire-engagement-ring', destination: '/blog/blue-sapphire-engagement-ring', permanent: true },
    { source: '/blue-sapphire-engagement-ring/', destination: '/blog/blue-sapphire-engagement-ring', permanent: true },
    { source: '/rose-gold-wedding-band', destination: '/blog/rose-gold-wedding-band', permanent: true },
    { source: '/rose-gold-wedding-band/', destination: '/blog/rose-gold-wedding-band', permanent: true },
    { source: '/diamond-pendant-necklaces', destination: '/blog/diamond-pendant-necklaces', permanent: true },
    { source: '/diamond-pendant-necklaces/', destination: '/blog/diamond-pendant-necklaces', permanent: true },
    { source: '/custom-ring-fire-yellow-diamonds', destination: '/blog/fancy-yellow-diamond-rings', permanent: true },
    { source: '/custom-ring-fire-yellow-diamonds/', destination: '/blog/fancy-yellow-diamond-rings', permanent: true },
    { source: '/unusual-engagement-rings-round-crossover', destination: '/blog/unusual-engagement-rings-round-crossover', permanent: true },
    { source: '/unusual-engagement-rings-round-crossover/', destination: '/blog/unusual-engagement-rings-round-crossover', permanent: true },
    { source: '/bez-ambar-aura-collection-multi-colored-stone-rings', destination: '/blog', permanent: true },
    { source: '/bez-ambar-aura-collection-multi-colored-stone-rings/', destination: '/blog', permanent: true },
    { source: '/snowflake-newsletter', destination: '/blog', permanent: true },
    { source: '/snowflake-newsletter/', destination: '/blog', permanent: true },
    { source: '/fancy-colored-diamond-jewelry', destination: '/blog/fancy-colored-diamond-jewelry', permanent: true },
    { source: '/fancy-colored-diamond-jewelry/', destination: '/blog/fancy-colored-diamond-jewelry', permanent: true },
    { source: '/fancy-intense-blue-diamond-ring', destination: '/blog/fancy-intense-blue-diamond-ring', permanent: true },
    { source: '/fancy-intense-blue-diamond-ring/', destination: '/blog/fancy-intense-blue-diamond-ring', permanent: true },
    { source: '/rose-cut-diamond-rings-by-bez-ambar', destination: '/blog/rose-cut-diamond-rings-by-bez-ambar', permanent: true },
    { source: '/rose-cut-diamond-rings-by-bez-ambar/', destination: '/blog/rose-cut-diamond-rings-by-bez-ambar', permanent: true },
    { source: '/white-gold-diamond-hoop-earrings', destination: '/blog/white-gold-diamond-hoop-earrings', permanent: true },
    { source: '/white-gold-diamond-hoop-earrings/', destination: '/blog/white-gold-diamond-hoop-earrings', permanent: true },
    { source: '/engagement-rings-for-women-heirloom-or-new', destination: '/blog/engagement-rings-for-women-heirloom-or-new', permanent: true },
    { source: '/engagement-rings-for-women-heirloom-or-new/', destination: '/blog/engagement-rings-for-women-heirloom-or-new', permanent: true },
    { source: '/chocolate-brown-diamond-rings', destination: '/blog/chocolate-brown-diamond-rings', permanent: true },
    { source: '/chocolate-brown-diamond-rings/', destination: '/blog/chocolate-brown-diamond-rings', permanent: true },
    { source: '/secret-behind-ring-sizing', destination: '/blog/secret-behind-ring-sizing', permanent: true },
    { source: '/secret-behind-ring-sizing/', destination: '/blog/secret-behind-ring-sizing', permanent: true },
    { source: '/sapphire-engagement-rings-yes-no', destination: '/blog/sapphire-engagement-rings-yes-no', permanent: true },
    { source: '/sapphire-engagement-rings-yes-no/', destination: '/blog/sapphire-engagement-rings-yes-no', permanent: true },
    { source: '/blue-diamond-rings', destination: '/blog/blue-diamond-rings', permanent: true },
    { source: '/blue-diamond-rings/', destination: '/blog/blue-diamond-rings', permanent: true },
    { source: '/why-a-1-carat-diamond', destination: '/blog/why-a-1-carat-diamond', permanent: true },
    { source: '/why-a-1-carat-diamond/', destination: '/blog/why-a-1-carat-diamond', permanent: true },
    { source: '/black-diamond-jewelry', destination: '/blog/black-diamond-jewelry', permanent: true },
    { source: '/black-diamond-jewelry/', destination: '/blog/black-diamond-jewelry', permanent: true },
    { source: '/is-a-pink-diamond-engagement-ring-right-for-you', destination: '/blog/is-a-pink-diamond-engagement-ring-right-for-you', permanent: true },
    { source: '/is-a-pink-diamond-engagement-ring-right-for-you/', destination: '/blog/is-a-pink-diamond-engagement-ring-right-for-you', permanent: true },
    { source: '/should-you-buy-emerald-engagement-rings', destination: '/blog/should-you-buy-emerald-engagement-rings', permanent: true },
    { source: '/should-you-buy-emerald-engagement-rings/', destination: '/blog/should-you-buy-emerald-engagement-rings', permanent: true },
    { source: '/choosing-your-diamond-earrings-studs', destination: '/blog/choosing-your-diamond-earrings-studs', permanent: true },
    { source: '/choosing-your-diamond-earrings-studs/', destination: '/blog/choosing-your-diamond-earrings-studs', permanent: true },
    { source: '/online-jewelry-stores', destination: '/blog/online-jewelry-stores', permanent: true },
    { source: '/online-jewelry-stores/', destination: '/blog/online-jewelry-stores', permanent: true },
    { source: '/choosing-semi-precious-stones', destination: '/blog/choosing-semi-precious-stones', permanent: true },
    { source: '/choosing-semi-precious-stones/', destination: '/blog/choosing-semi-precious-stones', permanent: true },
    { source: '/cushion-cut-diamond-earrings-video', destination: '/blog/cushion-cut-diamond-earrings-video', permanent: true },
    { source: '/cushion-cut-diamond-earrings-video/', destination: '/blog/cushion-cut-diamond-earrings-video', permanent: true },
    { source: '/princess-cut-diamond-earrings', destination: '/blog/princess-cut-diamond-earrings', permanent: true },
    { source: '/princess-cut-diamond-earrings/', destination: '/blog/princess-cut-diamond-earrings', permanent: true },
    { source: '/the-los-angeles-diamond-district', destination: '/blog/the-los-angeles-diamond-district', permanent: true },
    { source: '/the-los-angeles-diamond-district/', destination: '/blog/the-los-angeles-diamond-district', permanent: true },
    { source: '/blue-diamond-ring-vs-blue-sapphire-diamond-ring', destination: '/blog/blue-diamond-ring-vs-blue-sapphire-diamond-ring', permanent: true },
    { source: '/blue-diamond-ring-vs-blue-sapphire-diamond-ring/', destination: '/blog/blue-diamond-ring-vs-blue-sapphire-diamond-ring', permanent: true },
    { source: '/the-return-of-pear-shaped-diamond-rings', destination: '/blog/the-return-of-pear-shaped-diamond-rings', permanent: true },
    { source: '/the-return-of-pear-shaped-diamond-rings/', destination: '/blog/the-return-of-pear-shaped-diamond-rings', permanent: true },
    { source: '/diamond-hoop-earrings-guide', destination: '/blog/diamond-hoop-earrings-guide', permanent: true },
    { source: '/diamond-hoop-earrings-guide/', destination: '/blog/diamond-hoop-earrings-guide', permanent: true },
    { source: '/what-is-an-asscher-cut-diamond', destination: '/blog/what-is-an-asscher-cut-diamond', permanent: true },
    { source: '/what-is-an-asscher-cut-diamond/', destination: '/blog/what-is-an-asscher-cut-diamond', permanent: true },
    // /retailers index — new site has no listing page; individual retailer slugs handled above
    { source: '/retailers', destination: '/contact', permanent: true },
    // Remaining WP blog post slugs not in the top-performer list → base blog page
    { source: '/be-productive-while-working-on-the-road', destination: '/blog', permanent: true },
    { source: '/be-productive-while-working-on-the-road/', destination: '/blog', permanent: true },
    { source: '/bezambar-blaze-cut-diamonds', destination: '/blog', permanent: true },
    { source: '/bezambar-blaze-cut-diamonds/', destination: '/blog', permanent: true },
    { source: '/bezambar-princess-cut-diamonds', destination: '/blog', permanent: true },
    { source: '/bezambar-princess-cut-diamonds/', destination: '/blog', permanent: true },
    { source: '/how-many-words-are-your-pictures-worth', destination: '/blog', permanent: true },
    { source: '/how-many-words-are-your-pictures-worth/', destination: '/blog', permanent: true },
    { source: '/new-copywriting-positions-available', destination: '/blog', permanent: true },
    { source: '/new-copywriting-positions-available/', destination: '/blog', permanent: true },
    { source: '/print-is-dead-long-live-print', destination: '/blog', permanent: true },
    { source: '/print-is-dead-long-live-print/', destination: '/blog', permanent: true },
    { source: '/ring-of-fire', destination: '/blog', permanent: true },
    { source: '/ring-of-fire/', destination: '/blog', permanent: true },
    { source: '/silvertooth-opens-new-gym-to-employees', destination: '/blog', permanent: true },
    { source: '/silvertooth-opens-new-gym-to-employees/', destination: '/blog', permanent: true },
    { source: '/the-modern-workspace', destination: '/blog', permanent: true },
    { source: '/the-modern-workspace/', destination: '/blog', permanent: true },

    // ── Old-homepage navigation (added 2026-09-29) ───────────────────────────
    // Crawled the live WP homepage: 64 unique internal links, 26 of which had no
    // rule here and would 404 on cutover. The first 20 landed immediately; the
    // remaining 4 (/easyfit-* and /the-gemstone-eternity-collection-2) were held
    // for a product decision and resolved by Kevin the same day — see the two
    // blocks at the end of this file. All 24 are now covered.
    //
    // Destinations are DB-verified, not route-verified. `/jewelry/wedding-bands`
    // and `/jewelry/engagement-rings` are prerendered from CATEGORIES and return
    // 200, but products.category holds neither value — both listings are empty.
    // The 10 band/engagement URLs below therefore land on /jewelry/bands and
    // /jewelry/rings, which have 6 and 16 active products.
    //
    // Exact paths only, no patterns: five of these are shaped /jewelry/<a>/<b>
    // and a pattern rule would shadow every real product URL.
    { source: '/fine-jewelry', destination: '/jewelry', permanent: true },
    { source: '/fine-jewelry/', destination: '/jewelry', permanent: true },
    { source: '/online-store', destination: '/jewelry', permanent: true },
    { source: '/online-store/', destination: '/jewelry', permanent: true },
    { source: '/bez-ambar-catalogs', destination: '/jewelry', permanent: true },
    { source: '/bez-ambar-catalogs/', destination: '/jewelry', permanent: true },
    { source: '/fine-jewelry-rings-bez-ambar', destination: '/jewelry/rings', permanent: true },
    { source: '/fine-jewelry-rings-bez-ambar/', destination: '/jewelry/rings', permanent: true },
    { source: '/fine-jewelry-earrings-bez-ambar', destination: '/jewelry/earrings', permanent: true },
    { source: '/fine-jewelry-earrings-bez-ambar/', destination: '/jewelry/earrings', permanent: true },
    { source: '/jewelry/earrings/hug-earrings', destination: '/jewelry/earrings', permanent: true },
    { source: '/jewelry/earrings/hug-earrings/', destination: '/jewelry/earrings', permanent: true },
    { source: '/fine-jewelry-bracelets-bez-ambar', destination: '/jewelry/bracelets', permanent: true },
    { source: '/fine-jewelry-bracelets-bez-ambar/', destination: '/jewelry/bracelets', permanent: true },
    { source: '/pendants-and-charms-by-bez-ambar', destination: '/jewelry/pendants', permanent: true },
    { source: '/pendants-and-charms-by-bez-ambar/', destination: '/jewelry/pendants', permanent: true },
    // Wedding-band family → /jewelry/bands (not /jewelry/wedding-bands, which is empty)
    { source: '/mens-wedding-bands', destination: '/jewelry/bands', permanent: true },
    { source: '/mens-wedding-bands/', destination: '/jewelry/bands', permanent: true },
    { source: '/diamond-band-rings', destination: '/jewelry/bands', permanent: true },
    { source: '/diamond-band-rings/', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/wedding-bands-for-women/diamond-bands', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/wedding-bands-for-women/diamond-bands/', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/wedding-bands-for-women/thin-diamond-band', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/wedding-bands-for-women/thin-diamond-band/', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/wedding-bands-for-women/wide-diamond-bands', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/wedding-bands-for-women/wide-diamond-bands/', destination: '/jewelry/bands', permanent: true },
    // Engagement/bridal family → /jewelry/rings (not /jewelry/engagement-rings, which is empty)
    { source: '/wedding-bridal', destination: '/jewelry/rings', permanent: true },
    { source: '/wedding-bridal/', destination: '/jewelry/rings', permanent: true },
    { source: '/engagement-rings-3-2', destination: '/jewelry/rings', permanent: true },
    { source: '/engagement-rings-3-2/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/solitaire-engagement-rings', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/solitaire-engagement-rings/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/three-stone-engagement-rings', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/three-stone-engagement-rings/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/gemstones', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/gemstones/', destination: '/jewelry/rings', permanent: true },
    // Brand + archive
    { source: '/world-of-bez-ambar', destination: '/about-bez-ambar', permanent: true },
    { source: '/world-of-bez-ambar/', destination: '/about-bez-ambar', permanent: true },
    { source: '/10-carat-diamond-ring', destination: '/archive', permanent: true },
    { source: '/10-carat-diamond-ring/', destination: '/archive', permanent: true },
    // EasyFit family → the Extent bracelets (Kevin, 2026-09-29). All five live
    // Extent pieces are products.category = 'bracelets'; there is no EXTENT row
    // in products.collection, so /collection/extent would be an empty page.
    // /jewelry/bracelets is the listing that actually shows all five.
    { source: '/easyfit-stretch-jewelry', destination: '/jewelry/bracelets', permanent: true },
    { source: '/easyfit-stretch-jewelry/', destination: '/jewelry/bracelets', permanent: true },
    { source: '/easyfit-stretchable-fine-jewelry', destination: '/jewelry/bracelets', permanent: true },
    { source: '/easyfit-stretchable-fine-jewelry/', destination: '/jewelry/bracelets', permanent: true },
    // Ring shanks is editorial, not a product family (Kevin, 2026-09-29: "should
    // likely be like a blog page"). No post covers it yet — blog_posts holds
    // split-shank-engagement-ring and diamond-eternity-bracelet-guide, neither
    // about the EasyFit shank. Interim destination is /blog, the real editorial
    // index (132 posts). NOT /journal — despite the name, /journal is a
    // client-side Instagram embed with zero articles in its HTML. Repoint to
    // /blog/<slug> once the post exists.
    { source: '/easyfit-ring-shanks', destination: '/blog', permanent: true },
    { source: '/easyfit-ring-shanks/', destination: '/blog', permanent: true },
    // Gemstone Eternity → /jewelry/bands (Kevin, 2026-09-29). The only DB match
    // is products.slug 'diamond-eternity', active = false with a null category,
    // so there is no collection or piece page to land on.
    { source: '/the-gemstone-eternity-collection-2', destination: '/jewelry/bands', permanent: true },
    { source: '/the-gemstone-eternity-collection-2/', destination: '/jewelry/bands', permanent: true },
    // WordPress /jewelry/<slug> product-category pages — phantoms. The new site has
    // only 8 CATEGORIES keys; every other slug in this shape title-cased into an
    // empty HTTP 200 (soft 404). 70 URLs, 445 clicks / 94,431 impressions per the
    // Sep-28 GSC export. Destinations approved by Kevin 2026-09-29. These MUST be
    // in place before a notFound() guard lands on /jewelry/[category], or the
    // traffic converts from soft 404 to hard 404 in one commit.
    // 
    // Bucket A — an existing live post answers the query (31 URLs).
    { source: '/jewelry/princess-cut-center', destination: '/blog/princess-cut-diamond-ring-guide', permanent: true },
    { source: '/jewelry/princess-cut-center/', destination: '/blog/princess-cut-diamond-ring-guide', permanent: true },
    { source: '/jewelry/pear-shape-diamond-rings', destination: '/blog/the-return-of-pear-shaped-diamond-rings', permanent: true },
    { source: '/jewelry/pear-shape-diamond-rings/', destination: '/blog/the-return-of-pear-shaped-diamond-rings', permanent: true },
    { source: '/jewelry/quadrillion-colors', destination: '/blog/quadrillion-cut-different-princess-cut', permanent: true },
    { source: '/jewelry/quadrillion-colors/', destination: '/blog/quadrillion-cut-different-princess-cut', permanent: true },
    { source: '/jewelry/emerald-cut-engagement-rings', destination: '/blog/should-you-buy-emerald-engagement-rings', permanent: true },
    { source: '/jewelry/emerald-cut-engagement-rings/', destination: '/blog/should-you-buy-emerald-engagement-rings', permanent: true },
    { source: '/jewelry/emerald-cut', destination: '/blog/should-you-buy-emerald-engagement-rings', permanent: true },
    { source: '/jewelry/emerald-cut/', destination: '/blog/should-you-buy-emerald-engagement-rings', permanent: true },
    { source: '/jewelry/cushion-cut-engagement-rings', destination: '/blog/cushion-cut-diamond-engagement-ring', permanent: true },
    { source: '/jewelry/cushion-cut-engagement-rings/', destination: '/blog/cushion-cut-diamond-engagement-ring', permanent: true },
    { source: '/jewelry/men-wedding-bands', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/jewelry/men-wedding-bands/', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/jewelry/men-wedding-bands/unique-men-wedding-band', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/jewelry/men-wedding-bands/unique-men-wedding-band/', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/jewelry/interval-mens-wedding-band', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/jewelry/interval-mens-wedding-band/', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/jewelry/harvard-classic-mens-wedding-band', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/jewelry/harvard-classic-mens-wedding-band/', destination: '/blog/mens-wedding-band-buying-guide', permanent: true },
    { source: '/jewelry/divine-cut', destination: '/blog/bez-ambars-new-patented-design-divine-cut-diamond', permanent: true },
    { source: '/jewelry/divine-cut/', destination: '/blog/bez-ambars-new-patented-design-divine-cut-diamond', permanent: true },
    { source: '/jewelry/tennis-bracelets', destination: '/blog/diamond-tennis-bracelet-guide', permanent: true },
    { source: '/jewelry/tennis-bracelets/', destination: '/blog/diamond-tennis-bracelet-guide', permanent: true },
    { source: '/jewelry/hoop-earrings', destination: '/blog/diamond-hoop-earrings-guide', permanent: true },
    { source: '/jewelry/hoop-earrings/', destination: '/blog/diamond-hoop-earrings-guide', permanent: true },
    { source: '/jewelry/halo-engagement-ring', destination: '/blog/halo-ring-setting', permanent: true },
    { source: '/jewelry/halo-engagement-ring/', destination: '/blog/halo-ring-setting', permanent: true },
    { source: '/jewelry/blaze-cut-diamond-and-baguette-wedding-bands', destination: '/blog/baguette-diamond-guide', permanent: true },
    { source: '/jewelry/blaze-cut-diamond-and-baguette-wedding-bands/', destination: '/blog/baguette-diamond-guide', permanent: true },
    { source: '/jewelry/stud-earrings-earrings', destination: '/blog/choosing-your-diamond-earrings-studs', permanent: true },
    { source: '/jewelry/stud-earrings-earrings/', destination: '/blog/choosing-your-diamond-earrings-studs', permanent: true },
    { source: '/jewelry/cluster-diamond-rings', destination: '/blog/blaze-halo-setting-makes-diamond-look-bigger', permanent: true },
    { source: '/jewelry/cluster-diamond-rings/', destination: '/blog/blaze-halo-setting-makes-diamond-look-bigger', permanent: true },
    { source: '/jewelry/bangle-bracelets', destination: '/blog/bangle-vs-bracelet-fine-jewelry', permanent: true },
    { source: '/jewelry/bangle-bracelets/', destination: '/blog/bangle-vs-bracelet-fine-jewelry', permanent: true },
    { source: '/jewelry/engagement-rings/pave-diamonds', destination: '/blog/pave-engagement-ring-guide', permanent: true },
    { source: '/jewelry/engagement-rings/pave-diamonds/', destination: '/blog/pave-engagement-ring-guide', permanent: true },
    { source: '/jewelry/pave-shank', destination: '/blog/pave-engagement-ring-guide', permanent: true },
    { source: '/jewelry/pave-shank/', destination: '/blog/pave-engagement-ring-guide', permanent: true },
    { source: '/jewelry/big-diamond-rings', destination: '/blog/5-carat-diamond-ring', permanent: true },
    { source: '/jewelry/big-diamond-rings/', destination: '/blog/5-carat-diamond-ring', permanent: true },
    { source: '/jewelry/blaze', destination: '/blog/blaze-cut-diamond', permanent: true },
    { source: '/jewelry/blaze/', destination: '/blog/blaze-cut-diamond', permanent: true },
    { source: '/jewelry/split-shank', destination: '/blog/split-shank-engagement-ring', permanent: true },
    { source: '/jewelry/split-shank/', destination: '/blog/split-shank-engagement-ring', permanent: true },
    { source: '/jewelry/engagement-rings/asscher-cut-engagement-rings', destination: '/blog/what-is-an-asscher-cut-diamond', permanent: true },
    { source: '/jewelry/engagement-rings/asscher-cut-engagement-rings/', destination: '/blog/what-is-an-asscher-cut-diamond', permanent: true },
    { source: '/jewelry/round-brilliant-engagement-rings', destination: '/blog/round-brilliant-cut-diamond-ring', permanent: true },
    { source: '/jewelry/round-brilliant-engagement-rings/', destination: '/blog/round-brilliant-cut-diamond-ring', permanent: true },
    { source: '/jewelry/solitaire', destination: '/blog/solitaire-engagement-ring-guide', permanent: true },
    { source: '/jewelry/solitaire/', destination: '/blog/solitaire-engagement-ring-guide', permanent: true },
    { source: '/jewelry/custom-designs', destination: '/blog/custom-jewelry-design-process', permanent: true },
    { source: '/jewelry/custom-designs/', destination: '/blog/custom-jewelry-design-process', permanent: true },
    { source: '/jewelry/drop-earrings', destination: '/blog/diamond-drop-earrings-guide', permanent: true },
    { source: '/jewelry/drop-earrings/', destination: '/blog/diamond-drop-earrings-guide', permanent: true },
    { source: '/jewelry/fancy-colored-diamonds', destination: '/blog/fancy-colored-diamond-jewelry', permanent: true },
    { source: '/jewelry/fancy-colored-diamonds/', destination: '/blog/fancy-colored-diamond-jewelry', permanent: true },
    { source: '/jewelry/diamond-side-stone-engagement-rings', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/jewelry/diamond-side-stone-engagement-rings/', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/jewelry/black-diamonds', destination: '/blog/black-diamond-jewelry', permanent: true },
    { source: '/jewelry/black-diamonds/', destination: '/blog/black-diamond-jewelry', permanent: true },
    // Bucket C — commercial intent → product listing, not editorial (27 URLs).
    // blaze-engagement-rings → /jewelry/rings is Kevin's explicit call; a dedicated
    // Blaze collection page would serve it better if one is ever built.
    { source: '/jewelry/wedding-bands-for-women', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/wedding-bands-for-women/', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/eternity-bands-wedding', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/eternity-bands-wedding/', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/gemstone-wedding-bands', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/gemstone-wedding-bands/', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/channel-set', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/channel-set/', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/wedding-sets', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/wedding-sets/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/pink-sapphire', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/pink-sapphire/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/blaze-engagement-rings', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/blaze-engagement-rings/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/jackets-of-fire-stud-earrings', destination: '/jewelry/earrings', permanent: true },
    { source: '/jewelry/jackets-of-fire-stud-earrings/', destination: '/jewelry/earrings', permanent: true },
    { source: '/jewelry/gemstone-eternity-necklace', destination: '/jewelry/necklaces', permanent: true },
    { source: '/jewelry/gemstone-eternity-necklace/', destination: '/jewelry/necklaces', permanent: true },
    { source: '/jewelry/the-rolling-pendants', destination: '/jewelry/pendants', permanent: true },
    { source: '/jewelry/the-rolling-pendants/', destination: '/jewelry/pendants', permanent: true },
    { source: '/jewelry/fine-jewelry', destination: '/jewelry', permanent: true },
    { source: '/jewelry/fine-jewelry/', destination: '/jewelry', permanent: true },
    { source: '/jewelry/cufflinks', destination: '/jewelry', permanent: true },
    { source: '/jewelry/cufflinks/', destination: '/jewelry', permanent: true },
    { source: '/jewelry/in-stock-ready-to-ship-jewelry-by-bez-ambar', destination: '/jewelry', permanent: true },
    { source: '/jewelry/in-stock-ready-to-ship-jewelry-by-bez-ambar/', destination: '/jewelry', permanent: true },
    { source: '/jewelry/online-specials', destination: '/jewelry', permanent: true },
    { source: '/jewelry/online-specials/', destination: '/jewelry', permanent: true },
    { source: '/jewelry/outlet', destination: '/jewelry', permanent: true },
    { source: '/jewelry/outlet/', destination: '/jewelry', permanent: true },
    { source: '/jewelry/most-popular', destination: '/jewelry', permanent: true },
    { source: '/jewelry/most-popular/', destination: '/jewelry', permanent: true },
    { source: '/jewelry/hand-drawings', destination: '/about-bez-ambar', permanent: true },
    { source: '/jewelry/hand-drawings/', destination: '/about-bez-ambar', permanent: true },
    { source: '/jewelry/bryani-collection', destination: '/archive', permanent: true },
    { source: '/jewelry/bryani-collection/', destination: '/archive', permanent: true },
    { source: '/jewelry/the-nikol-collection', destination: '/archive', permanent: true },
    { source: '/jewelry/the-nikol-collection/', destination: '/archive', permanent: true },
    { source: '/jewelry/the-paloma', destination: '/archive', permanent: true },
    { source: '/jewelry/the-paloma/', destination: '/archive', permanent: true },
    { source: '/jewelry/the-valentine-collection', destination: '/archive', permanent: true },
    { source: '/jewelry/the-valentine-collection/', destination: '/archive', permanent: true },
    { source: '/jewelry/online-store', destination: '/', permanent: true },
    { source: '/jewelry/online-store/', destination: '/', permanent: true },
    { source: '/jewelry/online-store/earrings-online-store', destination: '/', permanent: true },
    { source: '/jewelry/online-store/earrings-online-store/', destination: '/', permanent: true },
    { source: '/jewelry/online-store/bands-online-store', destination: '/', permanent: true },
    { source: '/jewelry/online-store/bands-online-store/', destination: '/', permanent: true },
    { source: '/jewelry/online-store/pendants-online-store', destination: '/', permanent: true },
    { source: '/jewelry/online-store/pendants-online-store/', destination: '/', permanent: true },
    { source: '/jewelry/online-store/page/4', destination: '/', permanent: true },
    { source: '/jewelry/online-store/page/4/', destination: '/', permanent: true },
    { source: '/jewelry/online-store/page/2', destination: '/', permanent: true },
    { source: '/jewelry/online-store/page/2/', destination: '/', permanent: true },
    // Bucket D — WordPress pagination artifacts, follow the parent (12 URLs).
    { source: '/jewelry/engagement-rings/page/2', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/page/2/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/page/4', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/page/4/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/page/9', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/page/9/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/page/11', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/engagement-rings/page/11/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/blaze-engagement-rings/page/2', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/blaze-engagement-rings/page/2/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/blaze-engagement-rings/page/3', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/blaze-engagement-rings/page/3/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/blaze-engagement-rings/page/4', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/blaze-engagement-rings/page/4/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/blaze-engagement-rings/page/6', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/blaze-engagement-rings/page/6/', destination: '/jewelry/rings', permanent: true },
    { source: '/jewelry/wedding-bands-for-women/page/2', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/wedding-bands-for-women/page/2/', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/wedding-bands-for-women/page/3', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/wedding-bands-for-women/page/3/', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/eternity-bands-wedding/page/2', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/eternity-bands-wedding/page/2/', destination: '/jewelry/bands', permanent: true },
    { source: '/jewelry/engagement-rings/three-stone-engagement-rings/page/2', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    { source: '/jewelry/engagement-rings/three-stone-engagement-rings/page/2/', destination: '/blog/three-stone-engagement-ring-guide', permanent: true },
    // HELD, deliberately unrouted (9 URLs) — do not add a rule without a decision:
    //   Bucket B, 8 URLs awaiting new content (mens-black-diamond-rings 41,931 impr,
    //   mens-diamond-rings, modern-mens-wedding-rings, baguette-wedding-bands-women,
    //   ring-enhancers-wedding, silvet-ring-enhancers, stretch-rings,
    //   easyfit-stretchable-band-collection/bracelets-easyfit-…
    //   /jewelry/100k-club — 55 clicks / 14,157 impr at position 8.3, but a 0.4% CTR
    //   at that position suggests the impressions are non-jewelry intent. Check the
    //   GSC query report before routing it (Kevin: possible new post).
]
